<?php

namespace Shiwuhao\Rbac\Tests;

use Illuminate\Console\Application;
use Shiwuhao\Rbac\Commands\CreateRole;
use Shiwuhao\Rbac\Commands\GeneratePermissions;


class CommandTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Application::starting(function (Application $artisan) {
            $artisan->resolveCommands([
                GeneratePermissions::class,
                CreateRole::class,
            ]);
        });
    }


    /**
     * @test
     */
    public function it_can_show_expected_output()
    {
        $this->artisan('rbac:auto-generate-actions')
            ->expectsOutput('Creation Successful')
            ->run();
    }
}